### ISSUE TITLE
Inclusion.....

### ISSUE THREAD

**Issue by cowboysdude** [LukeSkywalker92/MMM-DWD-WarnWeather#10]
Just wondering if you had time to chat about this module......

You can email me at johnw8017@gmail.com

Thanks!!

Sorry I know this isn't an issue.  :)

**Comment by LukeSkywalker92** [comment]
Just write me here. Maybe it’s helpful for others too.

**Comment by cowboysdude** [comment]
I don't see how ... I was thinking about incorporating this module into NOAA but right now I don't have time......so in my readme I'm suggesting people use your module for weather warnings.....
