### ISSUE TITLE
DWD_Name nicht eindeutig

### ISSUE THREAD

**Issue by habandy** [LukeSkywalker92/MMM-DWD-WarnWeather#13]
Hallo LukeSkywalker92, 

Kannst du dir bitte dein Modul etwas genauer anschauen? 

Ich habe das Problem, dass mein Ort "Vöhringen" gleich 2x in Deutschland auftaucht. 
Laut deiner Beschreibung soll man den Wert "DWD_Name" der interaktiven Karte von DWD übernehmen. 

Problem:  Beide Städte haben den selben Wert!  Dein Script spuckt daraufhin nur ein "Ort nicht gefunden!" aus.  Selbst die Angaben der Lat und Long funktionieren nicht. 

Was ebenfalls nicht funktioniert ist die Beschreibung aus dem anderen Issue ( https://github.com/LukeSkywalker92/MMM-DWD-WarnWeather/issues/8 ) 
Allerdings habe ich über diesen herausgefunden dass mein Ort Vöhringen im Pulldown-Menü als "Vöhringen (Kreis Neu-Ulm)" gelistet ist.  Doch weder dieser Wert, noch "Kreis Neu-Ulm" funktionieren. Einzig und allein der Wert "Neu-Ulm" funktioniert.  

Es läuft also irgendwas in Richtung "eindeutige Zuordnung" schief. 

Wäre cool wenn das gefixt wird, damit das nicht auch anderen ähnlich wie mir fast zwei kostbare Stunden "herumprobieren" kostet... 

:)

**Comment by habandy** [comment]
Und natürlich verstehe ich dass die Doku vom DWD dir das bestimmt alles andere als einfach macht... mir dreht sich von all der Doku schon der Schädel...

**Comment by lavolp3** [comment]
Du kannst hier besser die warnCellID benutzen.
Schau dir meinen PR an. in dem ist eine csv verlinkt aus der du die warnCellID deines Kreises bekommst.
Sie liegt hier:
https://www.dwd.de/DE/leistungen/opendata/help/warnungen/cap_warncellids_csv.csv

**Comment by habandy** [comment]
It's fixed now with that warnCellID. 
Thanks to all!
