### ISSUE TITLE
Query for the location

### ISSUE THREAD

**Issue by CGabo** [LukeSkywalker92/MMM-DWD-WarnWeather#2]
There are two links on the DWD site:

- The link in your readme.md (region)
http://www.dwd.de/DE/wetter/warnungen_landkreise/warnWetter_node.html

- Another for the specific location
http://www.dwd.de/DE/wetter/warnungen/warnWetter_node.html

Try as example “Weil am Rhein”
Can MMM-DWD-WarnWeather only query for the “Landkreis”?
Thanks

**Comment by LukeSkywalker92** [comment]
It can only query for the "Landkreis". 
The DWD does not provide the location specific data via JSON-files.
