### ISSUE TITLE
warnCellID gets different results than region (NAME)

### ISSUE THREAD

**Issue by lxne** [LukeSkywalker92/MMM-DWD-WarnWeather#24]
First: Thank you very much for the update.

Unfortunately somethings seems not quite right.

If I am not wrong this is warnCellID;NAME;;KURZNAME for the city I want.
> 809279112;Stadt Dingolfing;;Dingolfing;

When I use the warnCellID I get a weather warning.
If I use `region: "Stadt Dingolfing"` (the corresponding NAME) I do get no warning.
When using 'Dingolfing' (which would be 'KURZNAME') I get an error "City not found".
The following screenshots display the different results:

![Bildschirmfoto 2020-06-17 um 18 09 01](https://user-images.githubusercontent.com/13134654/84922598-5be57900-b0c6-11ea-91e9-1a685a70df3b.png)
![Bildschirmfoto 2020-06-17 um 18 10 25](https://user-images.githubusercontent.com/13134654/84922601-5d16a600-b0c6-11ea-8421-d4df9974d01d.png)

**Comment by kleinmantara** [comment]
yes I have the same problem

**Comment by lavolp3** [comment]
the latest PR should at least solve the  "City not found" issue.
Check back again with the region name when that is implemented.
Or try it out yourself by changing "NAME" to "KURZNAME" in node_helper.js

**Comment by lxne** [comment]
> the latest PR should at least solve the "City not found" issue.
> Check back again with the region name when that is implemented.
> Or try it out yourself by changing "NAME" to "KURZNAME" in node_helper.js

After changing "NAME" to "KURZNAME" in node_helper.js I do get the correct results (same as warnCellID) when using 'Dingolfing' (KURZNAME)!

**Comment by lavolp3** [comment]
Great! Thanks for confirming
