### ISSUE TITLE
Is this module sill maintained?

### ISSUE THREAD

**Issue by tommek83** [LukeSkywalker92/MMM-DWD-WarnWeather#28]
For me no region is working - only "Ort nicht gefunden".
Is this module working for anybody?

**Comment by lxne** [comment]
Turned on my MagicMirror just right now and WarnWeather works as expected.
I am using "region" to define the location.
Alternative ways should be 'warnCellID' and 'lat/lng'.

**Comment by lxne** [comment]
Tried a view locations from the map.
For example 'Prenzlau' or 'München-Sendling' are both working for me.

**Comment by tommek83** [comment]
I don't know how, but now it's working. 
I am shure I tried it the way I'm doing now - never the less thank you for your answers.
