### ISSUE TITLE
Disable display of module when there is no warning.

### ISSUE THREAD

**Issue by codac** [LukeSkywalker92/MMM-DWD-WarnWeather#29]
It would be nice to be able to prevent the module getting displayed at all when there is no warning.
The Addon MMM-RMV for example only shows information when there is actually coming a bus/train. Otherwise the module is not visible.

**Comment by MacG-DD** [comment]
It seems implemented by @spitzlbergerj (keyword: "hide header.innerHTML")
But it doesn't work properly. If you set `noWarningText: '', ` then the module disappears for one second after reloading. It should disappear if there is only the header of the module. But it doesn't.

**Comment by OberfragGER** [comment]
Sorry,
but this doesnt work. The module/ header still existst.
![image](https://user-images.githubusercontent.com/28652993/140809292-03cb2721-afc6-4fc1-99c9-02f813dcf177.png)

![image](https://user-images.githubusercontent.com/28652993/140809422-9a548cd0-4ae9-47d5-a226-8f6b25cac963.png)

Or did i something wrong?

**Comment by codac** [comment]
are you using a docker? if yes please restart the docker in order to grab the config.
if not try restarting the mm process.

**Comment by OberfragGER** [comment]
> are you using a docker? if yes please restart the docker in order to grab the config. if not try restarting the mm process.

No. Regular install.
I just restarted the pi. Same thing.

**Comment by codac** [comment]
Thats weird as it works on my installtion.
Please remove the noWarningText parameter, so that I can see if that gets hidden properly as I hide the header and the warning message.

Can you go into developer mode and check the html code of this part (especially for the header).

**Comment by OberfragGER** [comment]
Is not working
![image](https://user-images.githubusercontent.com/28652993/140956329-5b496e26-9481-4e47-9d7e-6dcaa2cd51ea.png)

![image](https://user-images.githubusercontent.com/28652993/140956506-6c1b6ee8-3892-49bc-95bf-dea4ce830bc3.png)

**Comment by codac** [comment]
I think your comment parameter is wrong. It is not supposed to be a „`“ sign, try a „//„ instead.
Furthermore the Developer information is fromthe console tab. I need the information from the Elemets Tab, the HTML code so to speak in order to further investigate.
It might helo as well to post your custom.css content fot this module if you use it.

**Comment by OberfragGER** [comment]
> I think your comment parameter is wrong. It is not supposed to be a „`“ sign, try a „//„ instead. Furthermore the Developer information is fromthe console tab. I need the information from the Elemets Tab, the HTML code so to speak in order to further investigate. It might helo as well to post your custom.css content fot this module if you use it.

Sorry,
the screenshot was cut. I already have the "//".

`    {
      module: 'MMM-DWD-WarnWeather',
      position: 'top_left',
      config: {
        region: 'Hamburg-Wandsbek',
        minutes: false,
//        noWarningText: '',
		hideNoWarning: true,
        severityThreshold: 2
      }
    },`
My custom.css doesnt include anything for this module.

Sorry for asking. You need this one?
![image](https://user-images.githubusercontent.com/28652993/141011275-8259d532-d905-4377-b1e1-b0282b523dff.png)
I really dont know how to copy this as a .html

**Comment by codac** [comment]
Ok, so the config file seeme to be correct. The custom.css is not involved. I need to check why the code is not triggered.

The html screenshot is totally fine, its just the wrong part of it.
On your Screenshot you can see a class called „region bottom left“ for example. Those are the notes for the different positions. As your config file says, the module is supposed to be in the „top_left“, please open this node in the developer mode in your browser.
After opening it, you will see a list of modules that are placed „top_left“. There you should see the module node for MMM-DWD-WarnWeather. Now open all nodes that are underneath the module and make a new screenshot.

I need to know as well, if there was a weather warning at this point or not.

**Comment by MacG-DD** [comment]
With `header: 'Wetterwarnungen', ` and  `hideNoWarning: true,` is no header shown when there is a weather warning.

Otherwise, it works. Nothing, not even a header, is displayed if there are no warnings and the warnings are displayed if there are any.

**Comment by codac** [comment]
@MacG-DD correct, I'll fix this soon.

**Comment by OberfragGER** [comment]
I think somehow is has to do something with MMM-remote-control or MMM-pages.
Still not working
![image](https://user-images.githubusercontent.com/28652993/142898858-dbc5e859-2822-4aee-851e-d5226b673fe1.png)

`    {
      module: 'MMM-DWD-WarnWeather',
      position: 'top_left',
      config: {
        region: 'Hamburg-Wandsbek',
        minutes: false,
		header: 'Wetterwarnungen',
        noWarningText: 'Keine Unwetterwarnungen',
		hideNoWarning: true,
        severityThreshold: 2
      }
    },`

**Comment by OberfragGER** [comment]
> Ok, so the config file seeme to be correct. The custom.css is not involved. I need to check why the code is not triggered.
> 
> The html screenshot is totally fine, its just the wrong part of it. On your Screenshot you can see a class called „region bottom left“ for example. Those are the notes for the different positions. As your config file says, the module is supposed to be in the „top_left“, please open this node in the developer mode in your browser. After opening it, you will see a list of modules that are placed „top_left“. There you should see the module node for MMM-DWD-WarnWeather. Now open all nodes that are underneath the module and make a new screenshot.
> 
> I need to know as well, if there was a weather warning at this point or not.

Hi,
now i switched to a LAN_Cable and can reach my Mirror without any Problems.

The region is "upper third" ( there is a small box on WetterWarnungen) So no error in this part.

![image](https://user-images.githubusercontent.com/28652993/142900826-ae4d777e-e7d7-4ffb-867a-0334235c616d.png)

**Comment by MacG-DD** [comment]
> I think somehow is has to do something with MMM-remote-control or MMM-pages. Still not working !
> 
> ` { module: 'MMM-DWD-WarnWeather', position: 'top_left', config: { region: 'Hamburg-Wandsbek', minutes: false, header: 'Wetterwarnungen', noWarningText: 'Keine Unwetterwarnungen', hideNoWarning: true, severityThreshold: 2 } },`

Remove in your config: `noWarningText: 'Keine Unwetterwarnungen',`

My MM has no problems with MMM-Remote-Control.
