### ISSUE TITLE
Error: Cannot find module ˋnode-fetchˋ after latest MagicMirror update

### ISSUE THREAD

**Issue by AWSW-de** [LukeSkywalker92/MMM-DWD-WarnWeather#43]
Hi,
I got this error today „Cannot find module ˋnode-fetchˋ“ after latest MagicMirror update. See pictures below.

I am running an Raspberry Pi 4 with the latest bullseye release.

After disabling this module the Magic Mirror did start again.

Thanks in advance. =)

![IMG_0116](https://github.com/LukeSkywalker92/MMM-DWD-WarnWeather/assets/34800740/9f2ec90a-c416-42b4-bf0f-b2bc7307f2ce)

![IMG_0117](https://github.com/LukeSkywalker92/MMM-DWD-WarnWeather/assets/34800740/2ff552c0-fe25-4874-8ba8-f180c4581057)

**Comment by devtobi** [comment]
I can confirm that as well. Same behaviour.

**Comment by rabbit83ka** [comment]
It's due to a change in node.js, that's why you have to install node-fetch manually (Version 2.x). From inside the module folder (../MagicMirror/modules/MMM-DWD-WarnWeather):
`npm install node-fetch@2`

**Comment by AWSW-de** [comment]
> It's due to a change in node.js, that's why you have to install node-fetch manually (Version 2.x). From inside the module folder (../MagicMirror/modules/MMM-DWD-WarnWeather): `npm install node-fetch@2`

Thanks! It works again now =)
