### ISSUE TITLE
Text is everytime left-aligned

### ISSUE THREAD

**Issue by Raipel** [LukeSkywalker92/MMM-DWD-WarnWeather#6]
Hello,
I like your Module very much! I set the position of the module to the right sight, under the calendar-module. When a calendar-entry has a long text, the complete WarnWetter-Module switch its position a bit to the middle, because the calendar-module walks near to the middle of the screen.
Can You tell me, how I can set the config, that the Warn-Wetter-module ist right-aligned ?

Sorry for my bad english. Thank You!
Greetings from Cologne!
Raipel

**Comment by LukeSkywalker92** [comment]
Hey,
thanks for the feedback. 
I will have a look when i find time.
Luke

**Comment by Sennahoj82** [comment]
Hi.

Set in your custom.css the code you see below.

`.MMM-DWD-WarnWeather .status{
text-align: right;
}`
