### ISSUE TITLE
Seems not to be working any more...

### ISSUE THREAD

**Issue by c-m0s** [LukeSkywalker92/MMM-DWD-WarnWeather#8]
Thanks very much for the module, I do like the idea very much!

Unfortunately, I don't get warnings displayed, even when selecting regions, that do have actual active warnings , according to the DWD-Website (https://www.dwd.de/DE/wetter/warnungen_gemeinden).

I tried to use the DWD_NAME as well as the NAME listed in this MAP and Table (https://maps.dwd.de/geoserver/dwd/wms?service=WMS&version=1.1.0&request=GetMap&layers=dwd:Warngebiete_Gemeinden&styles=&bbox=5.876914,47.270362,15.037507,55.044381&width=1024&height=868&srs=EPSG:4326&format=application/openlayers#) as region option in the modules config.

Any hints?
Please!

**Comment by d-Rickyy-b** [comment]
You need to take the name displayed on the website [here](https://www.dwd.de/DE/wetter/warnungen_landkreise/warnWetter_node.html?ort=Karlsruhe). In this case the correct name wouldn't be "Karlsruhe", but "Kreis und Stadt Karlsruhe".

Greetings Rico.

**Comment by c-m0s** [comment]
Thanks, Rico-

I tried that before, but now it is working actually. A weird region name though. (and yet another map to get it from).
![mmm-dwd-warnweather](https://user-images.githubusercontent.com/15260207/34648670-4f597610-f39e-11e7-8ede-802e713147ce.png)

```
{
		module: 'MMM-DWD-WarnWeather', //https://www.dwd.de/DE/leistungen/warnungen/wetterwarnungen.html
		position: 'top_right',
		header: 'Wetterwarnungen: RO',
		config: {
				region:"Stadt Rosenheim",
				changeColor: false,
				interval: 10 * 60 * 1000, // every 10 minutes
				loadingText: 'Warnungen werden geladen...',
				longversion: true,
				width: 45,
				noWarningText: 'Keine Warnungen'
			  }
},
```

**Comment by c-m0s** [comment]
Hi @LukeSkywalker92, Hi @d-Rickyy-b,
do you have additional tipps? Now I am looking for a region in and around Munich- but I can't find working region names, not on the (https://www.dwd.de/DE/wetter/warnungen_gemeinden)-Map nor on the one you suggested above.

what input does this module require?
I tried

- München,
- Stadt München
- Kreis und Stadt München
- München-Hadern
- München-Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln

I don't get it and would appreachiate a helping hand or eye very much..

**Comment by d-Rickyy-b** [comment]
@c-m0s you could try to use `München-Maxvorstadt` (the most central district I could find on the map). It seems that Munich is too big and was separated into multiple zones by the DWD and not taken as a whole. I have taken this from the ["geoserver"-Map](https://maps.dwd.de/geoserver/dwd/wms?service=WMS&version=1.1.0&request=GetMap&layers=dwd:Warngebiete_Gemeinden&styles=&bbox=5.876914,47.270362,15.037507,55.044381&width=1024&height=868&srs=EPSG:4326&format=application/openlayers#) on the DWD site.

![grafik](https://user-images.githubusercontent.com/5798157/64262263-205e3180-cf2e-11e9-9047-e858e1fb2530.png)

**Comment by c-m0s** [comment]
Thanks, @d-Rickyy-b 
but the DWD_Name seems not to be working for me and the alternative, that @LukeSkywalker92 suggests in the readme, using lat and lng is not working either..

**Comment by d-Rickyy-b** [comment]
Then @LukeSkywalker92 needs to check into it. My MagicMirror is currently shut off so no idea if it's Maybe because of 'API' changes?!

**Comment by c-m0s** [comment]
I‘d appreciate your support!

**Comment by d-Rickyy-b** [comment]
Hi @c-m0s, I know the issue is quite old now, but I just tried `München-Maxvorstadt` and it works fine.

![grafik](https://user-images.githubusercontent.com/5798157/74102415-8dac6900-4b43-11ea-9824-07ee50a17297.png)


![grafik](https://user-images.githubusercontent.com/5798157/74102398-740b2180-4b43-11ea-95af-1aabf0cb85e5.png)

**Comment by c-m0s** [comment]
Tried this for ages. Now I checked it up again and followed #15 
I changed my config to use WarnCellID as well - and know it finally works again.

-> Don't use the region and corresponding NAME, there is to much potential for errors.
