### ISSUE TITLE
Untransparent icons

### ISSUE THREAD

**Issue by d-Rickyy-b** [LukeSkywalker92/MMM-DWD-WarnWeather#9]
Hey there, thanks for the nice tool.

I'd appreciate if you could add transparent icons. The given icons are not transparent and hence cannot be used with a background image, which I use, because I won't use it as a mirror but as kind of digital picture frame with information on it.

![image](https://user-images.githubusercontent.com/5798157/34646435-2dcbe202-f368-11e7-8ae5-18d6f3ea5988.png)

**Comment by LukeSkywalker92** [comment]
Hi,

this is not possible with the method this module uses to change the color of the icons.
When you have a closer look at the image, which is used to generate the icons, you will understand it.
The inner part of each icon is transparent.
The color of the icon is then changed with the background attribute in css.

**Comment by d-Rickyy-b** [comment]
Hmm, I took a look at your code and it seems that you load a different sprite depending on the 'level' of the warning (see [this](https://github.com/LukeSkywalker92/MMM-DWD-WarnWeather/blob/250e3ec399b1126f91e9eb8aa4a6b928ca55a0d1/MMM-DWD-WarnWeather.js#L101-L105) code).

And as far as I was able to understand, you don't change the icon's color programmatically, but you just load a different resource for it.

I just took 10 minutes and edited the resource files with GIMP and it seems to work fine with a transparent background. But might be better to have the "official" transparent resources from you, since I modified the png, whereas you might have a GIMP/Photoshop file and can just remove the black background.

Greetings Rico :)

**Comment by LukeSkywalker92** [comment]
Ah sorry, this is in a pending pull request. Since I want to merge to that, I’m not going to change anything here.

**Comment by d-Rickyy-b** [comment]
Hey there :)

You don't have intentions to change that behaviour?

![grafik](https://user-images.githubusercontent.com/5798157/54299139-863eb180-45ba-11e9-97fd-b2f029352789.png)

Sadly your css also affects other modules.

**Comment by LukeSkywalker92** [comment]
Feel free to send a pull request.
